### ISSUE TITLE
question about evaluating

### ISSUE THREAD

**Issue by JoJo-ops** [MarcCote/iRBM#6]
i evaluating a model trained on binarized MNIST,enter python eval_model.py experiments/best_irbm_mnist/
   Then these appear

Loading dataset...  (data: 50,000; 10,000; 10,000)  0.49 sec.
Loading model... (irbm with 852 hidden units) 0.40 sec.
Estimating model's partition function with AIS(5000) and 100,000 temperatures.... AIS run: 0/5000 (using batch size of 5000)

After that，There is no movement.always like this.

**Comment by MarcCote** [comment]
Hi. Computing AIS is really expensive computationally. Are you using GPUs or CPU only? You could always try to lower the number of samples (more variance in the result but faster to compute) like so 
`python eval_model.py experiments/best_irbm_mnist/ --nb-samples 500`

Let me know if that works for you.

**Comment by JoJo-ops** [comment]
> Hi. Computing AIS is really expensive computationally. Are you using GPUs or CPU only? You could always try to lower the number of samples (more variance in the result but faster to compute) like so
> `python eval_model.py experiments/best_irbm_mnist/ --nb-samples 500`
> 
> Let me know if that works for you.

Hi.I use GPU like so：CUDA_VISIBLE_DEVICE=0 python eval_model.py experiments/best_irbm_mnist/
But it seems that the GPU is not been used.
I try to lower the number of sample just like you suggest.but it also dosen`t work.

**Comment by JoJo-ops** [comment]
> Hi. Computing AIS is really expensive computationally. Are you using GPUs or CPU only? You could always try to lower the number of samples (more variance in the result but faster to compute) like so
> `python eval_model.py experiments/best_irbm_mnist/ --nb-samples 500`
> 
> Let me know if that works for you.
it appear this error
AttributeError: module 'utils' has no attribute 'save_dict_to_json_file'

**Comment by MarcCote** [comment]
Since this code is using Theano, you need to set the corresponding Theano flag. Instead of `CUDA_VISIBLE_DEVICE=0` (or in addition to it, I'm not sure) set the following `THEANO_FLAGS='device=cuda0'`

**Comment by MarcCote** [comment]
Regarding the `AttributeError` I just pushed a fix for it. My guess is that a `utils` library was installed on your machine hiding the `utils` found in `iRBM.misc`. Let me know if that works now.

**Comment by JoJo-ops** [comment]
> Since this code is using Theano, you need to set the corresponding Theano flag. Instead of `CUDA_VISIBLE_DEVICE=0` (or in addition to it, I'm not sure) set the following `THEANO_FLAGS='device=cuda0'`

Thank you very much for your answer.it help me a lot

**Comment by MarcCote** [comment]
I'm glad I could help. I'm closing this issue then.
